name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  firebase_core: 2.3.0
  google_sign_in: 5.4.2
  firebase_auth: 4.1.4
  lottie: 2.0.0
  flutter_native_splash: 2.2.15
  introduction_screen: 3.1.0
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.5.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
    - assets/lottie/
    - assets/models/
  uses-material-design: true

